openapi: 3.1.0
info:
  version: 1.0.0
  title: Farmer API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: phakphoom.k@zeabix.com
  description: >
    This is an Farmer API to demonstrate features of the OpenAPI
servers:
  - url: http://localhost:3000
paths:
  /health-check:
    $ref: paths/healthCheck.yaml
components:
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
